#!/bin/bash

while :
do
  # nextdrop=`./ethereal --connection=https://api.orinocopay.com:8546/ ethgas end`
  # nextdrop=`./ethereal --connection=https://mainnet.infura.io/mew ethgas end`
  nextdrop=`./ethereal --connection=https://mainnet.infura.io/mew contract call --from=a34c6bcae6f46ac6470443ccea67d937f6060c7e --contract=0x8BBf4dD0f11B3a535660fD7fCB7158DaEBd3a17E --signature="RewardEnd()" --returns="uint256"`
  echo "Next drop at ${nextdrop}"
  now=`date +%s`
  waittime=$((nextdrop-now-2))
  sleep ${waittime}
  ./ethereal transaction send --connection=https://api.orinocopay.com:8546/ --from=a34c6bcae6f46ac6470443ccea67d937f6060c7e --to=0x5600C7049F9B7bfDf44Bfc23880790F67DECf067 --gasprice=81.3002gwei --gaslimit=1200000
  # ./ethereal transaction send --connection=https://api.orinocopay.com:8546/ --from=a34c6bcae6f46ac6470443ccea67d937f6060c7e --to=0x8BBf4dD0f11B3a535660fD7fCB7158DaEBd3a17E --data=0xa8faf6f0 --gasprice=100gwei --gaslimit=50000
  sleep 60
done
